export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e3ffe7 0%, #d9e7ff 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fceabb 0%, #f8b500 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #f6f5f5 0%, #fbfbfb 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #ffffff 0%, #f1f1f1 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fff6e5 0%, #f9d29d 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #fdfcfb 0%, #e2d1c3 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #fefcea 0%, #f1da36 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #e2f0f9 0%, #bbd2c5 100%)' },
];


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no more guesswork.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the “Why” Behind Answers",
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];
